# Generated by Django 5.2.8 on 2025-12-24 11:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0005_remove_order_address_remove_order_card_cvv_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_invite_link', models.URLField(blank=True, help_text='لینک دعوت سرور دیسکورد', null=True, verbose_name='لینک دعوت دیسکورد')),
                ('minecraft_server_ip', models.CharField(blank=True, help_text='آی\u200cپی یا دامنه سرور ماینکرفت', max_length=255, null=True, verbose_name='آی\u200cپی سرور ماینکرفت')),
                ('admin_info_text', models.TextField(blank=True, help_text='اطلاعات ادمین\u200cهای سرور (متن HTML مجاز است)', null=True, verbose_name='اطلاعات ادمین\u200cها')),
                ('additional_info', models.TextField(blank=True, help_text='هرگونه اطلاعات اضافی برای نمایش در صفحه More Info (HTML مجاز است)', null=True, verbose_name='اطلاعات اضافی')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'اطلاعات سایت',
                'verbose_name_plural': 'اطلاعات سایت',
            },
        ),
        migrations.CreateModel(
            name='WartCoinSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price_per_coin', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='قیمت پایه هر واحد وارت کوین - اگر تخفیف عمده تنظیم نشده باشد، از این قیمت استفاده می\u200cشود', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='قیمت پایه هر وارت کوین (تومان)')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات وارت کوین',
                'verbose_name_plural': 'تنظیمات وارت کوین',
            },
        ),
        migrations.CreateModel(
            name='BulkDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.PositiveIntegerField(help_text='حداقل تعداد وارت کوین برای دریافت این تخفیف', verbose_name='حداقل مقدار (وارت کوین)')),
                ('price_per_coin', models.DecimalField(decimal_places=2, help_text='قیمت هر واحد وارت کوین برای این بازه', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='قیمت هر وارت کوین (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, help_text='برای مرتب\u200cسازی - مقادیر کمتر اول نمایش داده می\u200cشوند', verbose_name='ترتیب')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تخفیف خرید عمده',
                'verbose_name_plural': 'تخفیف\u200cهای خرید عمده',
                'ordering': ['order', 'min_amount'],
                'unique_together': {('min_amount',)},
            },
        ),
        migrations.CreateModel(
            name='WartCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='موجودی (وارت کوین)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wart_coin', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کیف پول وارت کوین',
                'verbose_name_plural': 'کیف پول\u200cهای وارت کوین',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='WartCoinPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_amount', models.PositiveIntegerField(verbose_name='مقدار وارت کوین')),
                ('price_per_coin', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت هر واحد (تومان)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='قیمت کل (تومان)')),
                ('payment_status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('completed', 'پرداخت شده'), ('failed', 'پرداخت ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه پرداخت')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='شناسه تراکنش')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_purchases', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'خرید وارت کوین',
                'verbose_name_plural': 'خریدهای وارت کوین',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='WartCoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='مقدار مثبت برای افزودن، منفی برای کسر', max_digits=15, verbose_name='مقدار')),
                ('transaction_type', models.CharField(choices=[('purchase', 'خرید'), ('spend', 'خرج'), ('manual', 'دستی (ادمین)'), ('refund', 'بازپرداخت')], max_length=20, verbose_name='نوع تراکنش')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='دلیل')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='موجودی بعد از تراکنش')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تراکنش')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_transactions', to='orders.order', verbose_name='سفارش مرتبط')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.wartcoin', verbose_name='کیف پول')),
            ],
            options={
                'verbose_name': 'تراکنش وارت کوین',
                'verbose_name_plural': 'تراکنش\u200cهای وارت کوین',
                'ordering': ['-created'],
            },
        ),
    ]
