# Generated by Django 6.0 on 2026-02-21 15:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
        ('orders', '0005_remove_order_address_remove_order_card_cvv_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('galion', 'Galion (طلا)'), ('sickle', 'Sickle (نقره)'), ('knut', 'Knut (برنز)')], help_text='کد واحد پولی', max_length=20, unique=True, verbose_name='کد ارز')),
                ('name', models.CharField(help_text='نام کامل واحد پولی', max_length=100, verbose_name='نام')),
                ('symbol', models.CharField(help_text='نماد نمایشی (مثلاً G برای Galion)', max_length=10, verbose_name='نماد')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='قیمت هر واحد این ارز به تومان', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='قیمت هر واحد (تومان)')),
                ('is_active', models.BooleanField(default=True, help_text='آیا این ارز فعال است؟', verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, help_text='برای مرتب\u200cسازی در لیست\u200cها', verbose_name='ترتیب نمایش')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'ارز',
                'verbose_name_plural': 'ارزها',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(choices=[('galion', 'Galion (طلا)'), ('sickle', 'Sickle (نقره)'), ('knut', 'Knut (برنز)')], max_length=20, verbose_name='از ارز')),
                ('to_currency', models.CharField(choices=[('galion', 'Galion (طلا)'), ('sickle', 'Sickle (نقره)'), ('knut', 'Knut (برنز)')], max_length=20, verbose_name='به ارز')),
                ('from_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مقدار مبدا')),
                ('to_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مقدار مقصد')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='کارمزد')),
                ('exchange_rate', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='نرخ تبدیل')),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='درصد کارمزد')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تبدیل')),
            ],
            options={
                'verbose_name': 'تبدیل ارز',
                'verbose_name_plural': 'تبدیل\u200cهای ارز',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CurrencySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galion_to_sickle_rate', models.DecimalField(decimal_places=2, default=Decimal('17.00'), help_text='1 Galion = ? Sickle', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='نرخ تبدیل Galion به Sickle')),
                ('sickle_to_knut_rate', models.DecimalField(decimal_places=2, default=Decimal('29.00'), help_text='1 Sickle = ? Knut', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='نرخ تبدیل Sickle به Knut')),
                ('conversion_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='درصد کارمزد برای تبدیل ارز (مثلاً 2.00 برای 2%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='کارمزد تبدیل (درصد)')),
                ('galion_price_toman', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='قیمت Galion (تومان)')),
                ('sickle_price_toman', models.DecimalField(decimal_places=2, default=Decimal('58.82'), help_text='به صورت خودکار از قیمت Galion محاسبه می\u200cشود', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='قیمت Sickle (تومان)')),
                ('knut_price_toman', models.DecimalField(decimal_places=2, default=Decimal('2.03'), help_text='به صورت خودکار از قیمت Galion محاسبه می\u200cشود', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='قیمت Knut (تومان)')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات ارزی',
                'verbose_name_plural': 'تنظیمات ارزی',
            },
        ),
        migrations.CreateModel(
            name='CurrencyPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(choices=[('galion', 'Galion (طلا)'), ('sickle', 'Sickle (نقره)'), ('knut', 'Knut (برنز)')], max_length=20, verbose_name='نوع ارز')),
                ('currency_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مقدار ارز')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت هر واحد (تومان)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='قیمت کل (تومان)')),
                ('payment_status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('completed', 'پرداخت شده'), ('failed', 'پرداخت ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه پرداخت')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='شناسه تراکنش')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_purchases', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'خرید ارز',
                'verbose_name_plural': 'خریدهای ارز',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galion_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='موجودی Galion')),
                ('sickle_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='موجودی Sickle')),
                ('knut_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='موجودی Knut')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='currency_wallet', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کیف پول چند ارزی',
                'verbose_name_plural': 'کیف پول\u200cهای چند ارزی',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(choices=[('galion', 'Galion (طلا)'), ('sickle', 'Sickle (نقره)'), ('knut', 'Knut (برنز)')], max_length=20, verbose_name='نوع ارز')),
                ('amount', models.DecimalField(decimal_places=2, help_text='مقدار مثبت برای افزودن، منفی برای کسر', max_digits=15, verbose_name='مقدار')),
                ('transaction_type', models.CharField(choices=[('purchase', 'خرید'), ('spend', 'خرج'), ('manual', 'دستی (ادمین)'), ('refund', 'بازپرداخت'), ('conversion', 'تبدیل ارز')], max_length=20, verbose_name='نوع تراکنش')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='دلیل')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='موجودی بعد از تراکنش')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تراکنش')),
                ('conversion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.currencyconversion', verbose_name='تبدیل ارز مرتبط')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_transactions', to='orders.order', verbose_name='سفارش مرتبط')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.currencywallet', verbose_name='کیف پول')),
            ],
            options={
                'verbose_name': 'تراکنش ارزی',
                'verbose_name_plural': 'تراکنش\u200cهای ارزی',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='currencyconversion',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='accounts.currencywallet', verbose_name='کیف پول'),
        ),
    ]
