# Generated by Django 6.0 on 2026-06-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_currency_currencyconversion_currencysettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('new', '🆕 جدید'), ('pending_user', '⏳ منتظر پاسخ کاربر'), ('pending_admin', '⏳ منتظر پاسخ ادمین'), ('answered', '✅ پاسخ داده شده'), ('closed', '🔒 بسته شده'), ('reopened', '🔓 دوباره باز شده')], default='new', max_length=20, verbose_name='وضعیت'),
        ),
    ]
