# Generated by Django 5.2.8 on 2025-11-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_options_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='فروشگاه ماینکرفت', max_length=200, verbose_name='نام سایت')),
                ('background_image', models.ImageField(blank=True, help_text='عکس پس\u200cزمینه که در تمام صفحات سایت نمایش داده می\u200cشود', null=True, upload_to='site_settings/', verbose_name='عکس پس\u200cزمینه صفحه اصلی')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
