# Generated by Django 5.2.8 on 2025-11-16 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_monthly_options',
            field=models.BooleanField(default=False, help_text='اگر فعال باشد، می\u200cتوانید گزینه\u200cهای ماهانه برای این محصول اضافه کنید', verbose_name='دارای گزینه\u200cهای ماهانه'),
        ),
        migrations.CreateModel(
            name='ProductMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.PositiveIntegerField(help_text='مثلاً 1 برای یک ماه، 3 برای سه ماه', verbose_name='تعداد ماه')),
                ('original_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت اصلی (تومان)')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=0, help_text='اگر خالی باشد، از قیمت اصلی استفاده می\u200cشود', max_digits=10, null=True, verbose_name='قیمت با تخفیف (تومان)')),
                ('image', models.ImageField(blank=True, help_text='عکس مخصوص این گزینه ماهانه (اختیاری)', null=True, upload_to='products/months/%Y/%m/%d', verbose_name='عکس')),
                ('description', models.TextField(help_text='توضیحات کامل این گزینه ماهانه', verbose_name='توضیحات کامل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, help_text='برای مرتب\u200cسازی گزینه\u200cها', verbose_name='ترتیب نمایش')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_options', to='shop.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'گزینه ماهانه',
                'verbose_name_plural': 'گزینه\u200cهای ماهانه',
                'ordering': ['order', 'months'],
                'unique_together': {('product', 'months')},
            },
        ),
    ]
