# Generated by Django 5.2.8 on 2025-12-24 11:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_sitesettings_server_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wart_coin_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='قیمت محصول به وارت کوین - این قیمت برای خرید استفاده می\u200cشود', max_digits=10, verbose_name='قیمت (وارت کوین)'),
        ),
        migrations.AddField(
            model_name='productmonth',
            name='wart_coin_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='قیمت این گزینه به وارت کوین', max_digits=10, verbose_name='قیمت (وارت کوین)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, help_text='قیمت قدیمی - فقط برای نمایش استفاده می\u200cشود', max_digits=10, verbose_name='قیمت (تومان)'),
        ),
        migrations.AlterField(
            model_name='productmonth',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='قیمت قدیمی - فقط برای نمایش', max_digits=10, null=True, verbose_name='قیمت با تخفیف (تومان)'),
        ),
        migrations.AlterField(
            model_name='productmonth',
            name='original_price',
            field=models.DecimalField(decimal_places=0, help_text='قیمت قدیمی - فقط برای نمایش', max_digits=10, verbose_name='قیمت اصلی (تومان)'),
        ),
    ]
