# Generated by Django 6.0 on 2026-02-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_wart_coin_price_productmonth_wart_coin_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, help_text='توضیحات و مشخصات کامل محصول که در صفحه مشخصات نمایش داده می\u200cشود', null=True, verbose_name='مشخصات کامل محصول'),
        ),
    ]
