# Generated by Django 6.0 on 2026-02-18 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('normal', 'محصول معمولی'), ('rank', 'رنک'), ('kit', 'کیت')], default='normal', help_text='مشخص کنید این محصول رنک است، کیت است یا محصول معمولی', max_length=20, verbose_name='نوع محصول'),
        ),
        migrations.CreateModel(
            name='KitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نام آیتم / قابلیت')),
                ('description', models.TextField(blank=True, help_text='توضیحات کوتاه درباره این آیتم (اختیاری)', null=True, verbose_name='توضیحات')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_items', to='shop.product', verbose_name='محصول (کیت)')),
            ],
            options={
                'verbose_name': 'آیتم کیت',
                'verbose_name_plural': 'آیتم\u200cهای کیت',
                'ordering': ['order', 'id'],
            },
        ),
    ]
