# Generated by Django 6.0 on 2026-02-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_product_type_kititem'),
    ]

    operations = [
        migrations.AddField(
            model_name='kititem',
            name='enchantments',
            field=models.TextField(blank=True, help_text='انچنت\u200cهای این آیتم (هر انچنت در یک خط جداگانه، مثال: sharpness II)', null=True, verbose_name='انچنت\u200cها'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, help_text='برای رنک\u200cها: fly : tick -- spawner : cross -- (هر خط با -- جدا می\u200cشود، tick = تیک سبز، cross/zarb = ضربدر قرمز). برای سایر محصولات: متن عادی', null=True, verbose_name='مشخصات کامل محصول'),
        ),
    ]
