# Generated by Django 6.0 on 2026-06-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_kititem_enchantments_alter_product_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='luckperms_group',
            field=models.CharField(blank=True, help_text='نام دقیق گروه روی سرور (مثلاً vip+). اگر خالی باشد از config/rank_mapping.json استفاده می\u200cشود.', max_length=64, verbose_name='گروه LuckPerms'),
        ),
    ]
