# Generated by Django 5.2.8 on 2025-11-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه پرداخت'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('completed', 'پرداخت شده'), ('failed', 'پرداخت ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=50, verbose_name='وضعیت پرداخت'),
        ),
    ]
