# Generated by Django 5.2.8 on 2025-11-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_id_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_cvv',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='CVV2'),
        ),
        migrations.AddField(
            model_name='order',
            name='card_expiry_month',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='ماه انقضا'),
        ),
        migrations.AddField(
            model_name='order',
            name='card_expiry_year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='سال انقضا'),
        ),
        migrations.AddField(
            model_name='order',
            name='card_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام دارنده کارت'),
        ),
        migrations.AddField(
            model_name='order',
            name='card_number',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='شماره کارت'),
        ),
    ]
