# Generated by Django 5.2.8 on 2025-12-24 11:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_address_alter_order_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_cvv',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_expiry_month',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_expiry_year',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_holder_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='minecraft_username',
            field=models.CharField(blank=True, help_text='نام کاربری Minecraft برای دریافت آیتم', max_length=16, null=True, verbose_name='نام کاربری ماینکرفت'),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='شناسه منحصر به فرد برای این سفارش', max_length=100, null=True, unique=True, verbose_name='شناسه تراکنش'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='order',
            name='wart_coin_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='مقدار وارت کوین پرداخت شده'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='month_option_id',
            field=models.PositiveIntegerField(blank=True, help_text='اگر این آیتم از گزینه\u200cهای ماهانه است', null=True, verbose_name='شناسه گزینه ماهانه'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='wart_coin_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='قیمت هر واحد به وارت کوین در زمان خرید', max_digits=10, verbose_name='قیمت (وارت کوین)'),
        ),
    ]
