# Generated by Django 6.0 on 2026-04-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_address_remove_order_card_cvv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rank_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='rank_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
