# Generated by Django 6.0 on 2026-06-30 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_rank_applied_order_rank_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankProvisionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=128, unique=True, verbose_name='کلید یکتا')),
                ('payload', models.JSONField(default=dict, verbose_name='داده درخواست')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('applied', 'اعمال شد'), ('retry', 'تلاش مجدد'), ('failed', 'ناموفق'), ('dead_letter', 'صف مرده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='تعداد تلاش')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='تلاش بعدی')),
                ('last_error', models.TextField(blank=True, verbose_name='آخرین خطا')),
                ('bridge_response', models.JSONField(blank=True, null=True, verbose_name='پاسخ bridge')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_jobs', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'کار اعمال رنک',
                'verbose_name_plural': 'کارهای اعمال رنک',
                'ordering': ('-created',),
            },
        ),
    ]
